# Generated by Django 3.2.15 on 2022-08-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='system_event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_event_type', to='system.systemeventtype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='atlima_obj_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_model', to='system.systemobject'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_used', to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notification',
            name='system_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_event_notify', to='system.systemevent'),
        ),
    ]
