# Generated by Django 3.2.15 on 2022-08-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='native_patronym',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
