# Generated by Django 3.2.15 on 2022-08-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_native_patronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
