# Generated by Django 3.2.15 on 2022-08-13 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_key', models.CharField(max_length=128)),
                ('order_id', models.CharField(max_length=128)),
                ('success', models.BooleanField()),
                ('status', models.CharField(max_length=32)),
                ('payment_id', models.IntegerField()),
                ('error_code', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('card_id', models.IntegerField()),
                ('pan', models.CharField(max_length=16)),
                ('expiration_date', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_code', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=128)),
                ('weight_in_list', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=512, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8)),
                ('discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('limit', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('init', 'Initialization'), ('finish_authorize', 'Finish Authorization'), ('add_card', 'Add Card'), ('attach_card', 'Attach Card'), ('remove_card', 'Remove Card'), ('card_list', 'Card List'), ('cancel', 'Cancel Payment')], default='init', max_length=128)),
                ('information_type', models.CharField(choices=[('Bank Request', 'Request'), ('Bank Response', 'Response')], default='Bank Request', max_length=128)),
                ('terminal_key', models.CharField(max_length=128)),
                ('amount', models.CharField(blank=True, max_length=128, null=True)),
                ('order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('customer_key', models.CharField(blank=True, max_length=256, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('recurrent', models.CharField(blank=True, max_length=3, null=True)),
                ('success', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('error_code', models.CharField(blank=True, max_length=4, null=True)),
                ('card_data', models.CharField(blank=True, max_length=4096, null=True)),
                ('card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('exp', models.CharField(blank=True, max_length=10, null=True)),
                ('card_holder', models.CharField(blank=True, max_length=512, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('check_type', models.CharField(blank=True, max_length=10, null=True)),
                ('request_key', models.CharField(blank=True, max_length=512, null=True)),
                ('card_id', models.CharField(blank=True, max_length=128, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('send_mail', models.BooleanField(blank=True, null=True)),
                ('info_email', models.CharField(blank=True, max_length=256, null=True)),
                ('rebill_id', models.CharField(blank=True, max_length=256, null=True)),
                ('pay_form', models.CharField(blank=True, max_length=1024, null=True)),
                ('receipt', models.JSONField(blank=True, null=True)),
                ('redirect_due_date', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('details', models.CharField(blank=True, max_length=1024, null=True)),
                ('md', models.CharField(blank=True, max_length=64, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceConfigurationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='money.priceconfiguration')),
            ],
            options={
                'verbose_name': 'price configuration Translation',
                'db_table': 'money_priceconfiguration_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=128)),
                ('object_id', models.PositiveBigIntegerField()),
                ('amount', models.PositiveBigIntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.order')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='money.promocode')),
            ],
        ),
    ]
