# Generated by Django 3.2.15 on 2022-08-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRefereeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Main Referee'), (2, 'Main Referee Deputy'), (3, 'Main Secretary'), (4, 'Referee'), (5, 'Senior Exercise Referee'), (6, 'Senior Referee of the Exercise Group'), (7, 'Weaponry Referee'), (8, 'Technical Referee')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Waiting'), (2, 'Approved'), (3, 'Dismissed'), (4, 'Moderated')], default=1)),
                ('dismiss_reason', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefereeGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Satisfactorily'), (2, 'Unsatisfactorily')], default=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefereeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Main Referee'), (2, 'Main Referee Deputy'), (3, 'Main Secretary'), (4, 'Referee'), (5, 'Senior Exercise Referee'), (6, 'Senior Referee of the Exercise Group'), (7, 'Weaponry Referee'), (8, 'Technical Referee')], default=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
