# Generated by Django 3.2.15 on 2022-08-13 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeslot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_referee_slot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refereegrade',
            name='referee_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referee.refereeslot'),
        ),
        migrations.AddField(
            model_name='eventrefereeinvite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventrefereeinvite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_judges_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
