# Generated by Django 3.2.15 on 2022-08-13 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipsc', '0002_initial'),
        ('referee', '0002_initial'),
        ('sport', '0002_initial'),
        ('common', '0002_initial'),
        ('money', '0002_initial'),
        ('location', '0001_initial'),
        ('sport_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_for_slot', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='sport_events.event'),
        ),
        migrations.AddField(
            model_name='eventproperty',
            name='disciplines',
            field=models.ManyToManyField(to='ipsc.Discipline'),
        ),
        migrations.AddField(
            model_name='eventproperty',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.sport'),
        ),
        migrations.AddField(
            model_name='eventformattranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='sport_events.eventformat'),
        ),
        migrations.AddField(
            model_name='eventevskstatustranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='sport_events.eventevskstatus'),
        ),
        migrations.AddField(
            model_name='event',
            name='administrators',
            field=models.ManyToManyField(related_name='administrators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_city', to='location.city'),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_country', to='location.country'),
        ),
        migrations.AddField(
            model_name='event',
            name='courses',
            field=models.ManyToManyField(to='ipsc.Course'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_registration_price', to='money.currency'),
        ),
        migrations.AddField(
            model_name='event',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='evsk',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport_events.eventevskstatus'),
        ),
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_format', to='sport_events.eventformat'),
        ),
        migrations.AddField(
            model_name='event',
            name='interested',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to='common.organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='price_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_price_option', to='money.priceconfiguration'),
        ),
        migrations.AddField(
            model_name='event',
            name='promocodes',
            field=models.ManyToManyField(to='money.PromoCode'),
        ),
        migrations.AddField(
            model_name='event',
            name='properties',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sport_events.eventproperty'),
        ),
        migrations.AddField(
            model_name='event',
            name='referee_slots',
            field=models.ManyToManyField(to='referee.RefereeSlot'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_region', to='location.region'),
        ),
        migrations.AddField(
            model_name='event',
            name='slots',
            field=models.ManyToManyField(to='sport_events.Slot'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_sport_type', to='sport.sport'),
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(to='ipsc.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='eventtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='eventformattranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='eventevskstatustranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
