# Generated by Django 3.2.15 on 2022-08-13 20:18

from django.db import migrations, models
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('user_ip', models.CharField(blank=True, max_length=120, null=True)),
                ('reason', models.IntegerField(choices=[(1, 'SPAM'), (2, 'FORBIDDEN CONTENT'), (3, 'FRAUD'), (4, 'COPYRIGHT'), (5, 'VIOLENCE'), (6, 'PERSONAL DATA')], default=1)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'APPROVED'), (2, 'DECLINED')], default=None, null=True)),
                ('moderator_ip', models.CharField(blank=True, max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32, verbose_name='Action')),
                ('data', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=128)),
                ('status', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmailTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('template_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'email template Translation',
                'db_table': 'common_emailtemplate_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('For User', 'For User'), ('For Organizer', 'For Organizer')], default='For User', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventOfferTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.CharField(max_length=32000, verbose_name='text')),
            ],
            options={
                'verbose_name': 'event offer Translation',
                'db_table': 'common_eventoffer_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizers')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('site', models.URLField()),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('imported', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'organizer Translation',
                'db_table': 'common_organizer_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrivacySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_visibility', models.PositiveSmallIntegerField(choices=[(1, 'All'), (2, 'Only subscribers'), (3, 'Only me')], default=1)),
                ('email_visibility', models.PositiveSmallIntegerField(choices=[(1, 'All'), (2, 'Only subscribers'), (3, 'Only me')], default=1)),
                ('want_to_get_mails_from_atlima', models.BooleanField(default=False)),
                ('who_can_send_messages', models.PositiveSmallIntegerField(choices=[(1, 'All'), (2, 'Only subscribers'), (3, 'Only me')], default=1)),
            ],
        ),
    ]
