# Generated by Django 3.2.15 on 2022-08-14 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organizer_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_organizer_admin_id', to='common.organizer', verbose_name='Organizer')),
                ('profile_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_profile_admin_id', to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
            options={
                'unique_together': {('organizer_record', 'profile_record')},
            },
        ),
    ]
