# Generated by Django 3.2.15 on 2022-08-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytranslation',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
