# Generated by Django 3.2.15 on 2022-08-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_countrytranslation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regiontranslation',
            old_name='text',
            new_name='title',
        ),
    ]
