# Generated by Django 3.2.15 on 2022-08-13 20:18

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedCourseResultForSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(blank=True, null=True, verbose_name='Result UUID')),
                ('result_type', models.IntegerField(choices=[(1, 'Guncheck'), (2, 'Course result'), (3, 'Disqualification (DNS/DQ)')], default=2)),
                ('A', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('C', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('D', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('M', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('NS', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('T', models.FloatField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, choices=[(1, 'Super Junior'), (2, 'Junior'), (3, 'Senior'), (4, 'Super Senior'), (5, 'Lady'), (6, 'Regular')], null=True)),
                ('power_factor', models.IntegerField(blank=True, choices=[(1, 'MINOR'), (2, 'MAJOR')], null=True)),
                ('strong_hand', models.IntegerField(blank=True, choices=[(2, 'Right'), (1, 'Left')], null=True)),
                ('cancellation', models.IntegerField(blank=True, choices=[(1, 'Did not started'), (2, 'Disqualified')], default=None, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='result_selfies')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='courses')),
                ('scoring_shoots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minimum_shoots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('illustration', models.ImageField(upload_to='courses')),
                ('scoring_paper', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CoursePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'course Translation',
                'db_table': 'ipsc_course_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_type', models.IntegerField(blank=True, choices=[(1, 'Individual Competitions'), (2, 'Team competitions (4 ppl)'), (3, 'Duel')], default=1, null=True)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('active', models.BooleanField(default=True)),
                ('standart_speed_courses', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DisqualificationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='divisions')),
                ('can_be_minor', models.BooleanField(default=True)),
                ('can_be_major', models.BooleanField(default=True)),
                ('custom_style', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_number', models.PositiveIntegerField()),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('squad_date', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_result', models.CharField(choices=[('NS', 'NS'), ('A', 'A'), ('AC', 'AC'), ('ACD', 'ACD')], default='ACD', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='targets')),
                ('paper', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TargetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsc.target')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weapons')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WeaponTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='ipsc.weapon')),
            ],
            options={
                'verbose_name': 'weapon Translation',
                'db_table': 'ipsc_weapon_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsc.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='TargetTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='ipsc.targettype')),
            ],
            options={
                'verbose_name': 'target type Translation',
                'db_table': 'ipsc_targettype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TargetSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('alpha_cost', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('course_target_array', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsc.course')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipsc.target')),
            ],
        ),
        migrations.CreateModel(
            name='SlotResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_points', models.FloatField(default=0)),
                ('stage_points', models.FloatField(default=0)),
                ('hit_factor', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsc.course')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause', models.CharField(max_length=16)),
                ('cost_in_seconds', models.PositiveSmallIntegerField(default=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('disciplines', models.ManyToManyField(to='ipsc.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='DivisionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='ipsc.division')),
            ],
            options={
                'verbose_name': 'division Translation',
                'db_table': 'ipsc_division_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='division',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsc.weapon'),
        ),
        migrations.CreateModel(
            name='DisqualificationReasonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='ipsc.disqualificationreason')),
            ],
            options={
                'verbose_name': 'disqualification reason Translation',
                'db_table': 'ipsc_disqualificationreason_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DisciplineTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='ipsc.discipline')),
            ],
            options={
                'verbose_name': 'discipline Translation',
                'db_table': 'ipsc_discipline_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='discipline',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipsc.division'),
        ),
    ]
