# Generated by Django 3.2.15 on 2022-08-13 20:18

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipsc', '0001_initial'),
        ('referee', '0001_initial'),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.sport'),
        ),
        migrations.AddField(
            model_name='coursetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='ipsc.course'),
        ),
        migrations.AddField(
            model_name='coursepenalty',
            name='aggregated_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsc.aggregatedcourseresultforslot'),
        ),
        migrations.AddField(
            model_name='coursepenalty',
            name='penalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsc.penalty'),
        ),
        migrations.AddField(
            model_name='aggregatedcourseresultforslot',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipsc.disqualificationreason'),
        ),
        migrations.AddField(
            model_name='aggregatedcourseresultforslot',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipsc.course'),
        ),
        migrations.AddField(
            model_name='aggregatedcourseresultforslot',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipsc.discipline'),
        ),
        migrations.AddField(
            model_name='aggregatedcourseresultforslot',
            name='referee_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referee.refereeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='weapontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='targettypetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='divisiontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='disqualificationreasontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='disciplinetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='coursetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
