# Generated by Django 3.2.15 on 2022-08-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.IntegerField(choices=[(1, 'Sport qualification'), (2, 'Referee qualification'), (3, 'Instructor qualification')], default=2)),
                ('category', models.IntegerField(choices=[(1, 'Junior referee'), (2, 'Sport referee III'), (3, 'Sport referee II'), (4, 'Sport referee I'), (5, 'Sport referee of the all-Russian')], default=1)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='related_document_file')),
                ('IROA', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('dismiss_reason', models.CharField(blank=True, max_length=4096, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
