# Generated by Django 3.2.15 on 2022-08-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport', '0001_initial'),
        ('qualification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialqualification',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_sport', to='sport.sport'),
        ),
    ]
