# Generated by Django 3.2.15 on 2022-08-14 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_rename_text_regiontranslation_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sks_member', models.BooleanField(default=False)),
                ('is_sks_president', models.BooleanField(default=False)),
                ('is_referee_collegium_member', models.BooleanField(default=False)),
                ('is_referee_collegium_president', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country', verbose_name='country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.region', verbose_name='region')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.sport', verbose_name='sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
